export * from './adminUser.service';
import { AdminUserService } from './adminUser.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './details.service';
import { DetailsService } from './details.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './learnHubs.service';
import { LearnHubsService } from './learnHubs.service';
export * from './links.service';
import { LinksService } from './links.service';
export * from './quizzes.service';
import { QuizzesService } from './quizzes.service';
export * from './student.service';
import { StudentService } from './student.service';
export * from './subscription.service';
import { SubscriptionService } from './subscription.service';
export * from './subscriptionPackage.service';
import { SubscriptionPackageService } from './subscriptionPackage.service';
export const APIS = [AdminUserService, AuthService, DashboardService, DetailsService, FileService, LearnHubsService, LinksService, QuizzesService, StudentService, SubscriptionService, SubscriptionPackageService];
