/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminUserDetailsDTO { 
    id?: string;
    email?: string | null;
    role?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    school?: string | null;
    city?: string | null;
    approvalStatus?: string | null;
}

