/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRegistrationStatsDTO } from './userRegistrationStatsDTO';
import { SubscriptionStatsDTO } from './subscriptionStatsDTO';
import { QuizStatsDTO } from './quizStatsDTO';
import { AdminStatsDTO } from './adminStatsDTO';
import { RecentActivityDTO } from './recentActivityDTO';
import { LearnHubStatsDTO } from './learnHubStatsDTO';


export interface AdminDashboardDTO { 
    stats?: AdminStatsDTO;
    recentActivities?: Array<RecentActivityDTO> | null;
    registrationStats?: Array<UserRegistrationStatsDTO> | null;
    learnHubStats?: Array<LearnHubStatsDTO> | null;
    quizStats?: Array<QuizStatsDTO> | null;
    subscriptionStats?: Array<SubscriptionStatsDTO> | null;
}

