/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateQuizzDTO { 
    question?: string | null;
    explanation?: string | null;
    points?: number;
    options?: string | null;
}

