/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateStudentBySchoolDTO { 
    firstName: string;
    lastName: string;
    email: string;
    currentClass: string;
    dateOfBirth: string;
    school: string;
    planId: string;
}

