/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateStudentBySupervisorDTO { 
    firstName?: string | null;
    lastName?: string | null;
    currentClass?: string | null;
    school?: string | null;
    dateOfBirth?: string;
}

