/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OptionDTO } from './optionDTO';


export interface CreateQuizzDTO { 
    question?: string | null;
    questionAudioId?: string | null;
    explanation?: string | null;
    explanationAudioId?: string | null;
    points?: number;
    options?: Array<OptionDTO> | null;
    quizType?: string | null;
}

