/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardStatsDTO } from './dashboardStatsDTO';
import { LearnHubProgressDTO } from './learnHubProgressDTO';


export interface DashboardDTO { 
    stats?: DashboardStatsDTO;
    latestLearnHubs?: Array<LearnHubProgressDTO> | null;
}

