/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FamilyMemberInput } from './familyMemberInput';


export interface FamilyRegistrationDTO { 
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    subscriptionPackageId: string;
    familyMembers: Array<FamilyMemberInput>;
    phoneNumber?: string | null;
}

