/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FamilyMemberInput { 
    firstName?: string | null;
    lastName?: string | null;
    /**
     * Class ID (Guid) or Class Name. Will be converted to Class ID internally.
     */
    currentClass?: string | null;
}

