/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeographicStatsDTO { 
    city?: string | null;
    userCount?: number;
    schoolCount?: number;
    revenue?: number;
}

