/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LearnHubStatsDTO { 
    id?: string;
    title?: string | null;
    subject?: string | null;
    classType?: string | null;
    difficulty?: number;
    isFree?: boolean;
    createdAt?: string;
    totalLinks?: number;
    totalQuizzes?: number;
    totalAttempts?: number;
    uniqueStudents?: number;
    averageScore?: number;
    completionRate?: number;
}

