/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateLinkDTO } from './createLinkDTO';


export interface LearnHubCreateDTO { 
    title?: string | null;
    description?: string | null;
    classType?: string | null;
    subject?: string | null;
    isFree?: boolean;
    links?: Array<CreateLinkDTO> | null;
}

