/**
 * TeachingBACKEND API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LearnHubProgressDTO {
  id?: string;
  title?: string | null;
  progressPercentage?: number;
  lastExercise?: string | null;
  lastActivityAt?: string | null;
  pointsEarned?: number;
  totalPossiblePoints?: number;
  lastExerciseLinkId?: string;
}

