/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateLinkDTO } from './createLinkDTO';
import { PackageTier } from './packageTier';


export interface LearnHubCreateDTO { 
    title?: string | null;
    description?: string | null;
    classType?: string | null;
    subject?: string | null;
    isFree?: boolean;
    requiredTier?: PackageTier;
    difficulty?: number;
    links?: Array<CreateLinkDTO> | null;
}
export namespace LearnHubCreateDTO {
}


