/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OptionDTO { 
    optionText?: string | null;
    isCorrect?: boolean;
    optionImageId?: string | null;
    optionImageUrl?: string | null;
}

