/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { SubscriptionPackage } from './subscriptionPackage';


export interface Payment { 
    id?: string;
    userId?: string | null;
    user?: User;
    email?: string | null;
    registrationType?: string | null;
    registrationData?: string | null;
    stripeSessionId?: string | null;
    stripePaymentIntentId?: string | null;
    amount?: number;
    currency?: string | null;
    status?: string | null;
    createdAt?: string;
    subscriptionPackageId?: string | null;
    subscriptionPackage?: SubscriptionPackage;
}

