/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuizStatsDTO { 
    id?: string;
    question?: string | null;
    learnHubTitle?: string | null;
    linkTitle?: string | null;
    points?: number;
    createdAt?: string;
    totalAttempts?: number;
    correctAttempts?: number;
    successRate?: number;
    averageTimeSpent?: number;
}

