/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecentActivityDTO { 
    id?: string;
    type?: string | null;
    description?: string | null;
    userName?: string | null;
    userRole?: string | null;
    timestamp?: string;
    icon?: string | null;
    metadata?: { [key: string]: any; } | null;
}

