/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './payment';


export interface RegistrationPlan { 
    id?: string;
    registrationPlanName?: string | null;
    type?: string | null;
    price?: number;
    stripeProductName?: string | null;
    payments?: Array<Payment> | null;
}

