/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './payment';
import { Subscription } from './subscription';


export interface RegistrationPlan { 
    id?: string;
    registrationPlanName?: string | null;
    type?: string | null;
    price?: number;
    monthlyPrice?: number;
    yearlyPrice?: number;
    stripeMonthlyPriceId?: string | null;
    stripeYearlyPriceId?: string | null;
    stripeProductId?: string | null;
    stripeProductName?: string | null;
    isFamilyPlan?: boolean;
    userType?: string | null;
    maxUsers?: number;
    isSubscription?: boolean;
    trialDays?: number;
    allowCancellation?: boolean;
    payments?: Array<Payment> | null;
    subscriptions?: Array<Subscription> | null;
}

