/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateStudentBySchoolDTO } from './createStudentBySchoolDTO';


export interface SchoolRegistrationDTO { 
    schoolName: string;
    email: string;
    phoneNumber: string;
    profession: string;
    city: string;
    postalCode: string;
    planId: string;
    students: Array<CreateStudentBySchoolDTO>;
}

