/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StudentQuizSubmissionDTO { 
    quizId?: string;
    answerId?: string | null;
    answerIds?: Array<string> | null;
    startedAt?: string | null;
}

