/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BillingInterval } from './billingInterval';
import { User } from './user';
import { SubscriptionStatus } from './subscriptionStatus';
import { SubscriptionPayment } from './subscriptionPayment';
import { SubscriptionPackage } from './subscriptionPackage';


export interface Subscription { 
    id?: string;
    userId?: string;
    user?: User;
    stripeSubscriptionId?: string | null;
    stripeCustomerId?: string | null;
    stripePriceId?: string | null;
    subscriptionPackageId?: string;
    subscriptionPackage?: SubscriptionPackage;
    status?: SubscriptionStatus;
    startDate?: string;
    endDate?: string | null;
    canceledAt?: string | null;
    currentPeriodStart?: string | null;
    currentPeriodEnd?: string | null;
    trialEnd?: string | null;
    currency?: string | null;
    amount?: number;
    interval?: BillingInterval;
    intervalCount?: number;
    registrationType?: string | null;
    registrationData?: string | null;
    createdAt?: string;
    updatedAt?: string;
    payments?: Array<SubscriptionPayment> | null;
}
export namespace Subscription {
}


