/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Subscription } from './subscription';
import { PaymentStatus } from './paymentStatus';


export interface SubscriptionPayment { 
    id?: string;
    subscriptionId?: string;
    subscription?: Subscription;
    stripePaymentIntentId?: string | null;
    stripeInvoiceId?: string | null;
    amount?: number;
    currency?: string | null;
    status?: PaymentStatus;
    paidAt?: string;
    createdAt?: string;
    periodStart?: string;
    periodEnd?: string;
}
export namespace SubscriptionPayment {
}


