/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BillingInterval } from './billingInterval';


export interface SubscriptionRequestDTO { 
    email: string;
    registrationType: string;
    planId: string;
    registrationData: string;
    billingInterval: BillingInterval;
    familyMemberCount?: number | null;
    couponCode?: string | null;
}
export namespace SubscriptionRequestDTO {
}


