/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionStatus } from './subscriptionStatus';
import { UserType } from './userType';


export interface SubscriptionStatsDTO { 
    id?: string;
    packageName?: string | null;
    userType?: UserType;
    status?: SubscriptionStatus;
    activeSubscriptions?: number;
    monthlyRevenue?: number;
    totalRevenue?: number;
    createdAt?: string;
    newSubscriptionsThisMonth?: number;
    cancellationsThisMonth?: number;
}
export namespace SubscriptionStatsDTO {
}


