/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BillingInterval } from './billingInterval';
import { Payment } from './payment';
import { Subscription } from './subscription';
import { UserType } from './userType';
import { PackageTier } from './packageTier';


export interface SubscriptionPackage { 
    id?: string;
    name?: string | null;
    description?: string | null;
    userType?: UserType;
    tier?: PackageTier;
    billingInterval?: BillingInterval;
    monthlyPrice?: number;
    yearlyPrice?: number;
    basePrice?: number | null;
    pricePerAdditionalMember?: number | null;
    minFamilyMembers?: number | null;
    maxFamilyMembers?: number | null;
    stripeMonthlyPriceId?: string | null;
    stripeYearlyPriceId?: string | null;
    maxUsers?: number;
    trialDays?: number;
    isActive?: boolean;
    createdAt?: string;
    updatedAt?: string;
    payments?: Array<Payment> | null;
    subscriptions?: Array<Subscription> | null;
}
export namespace SubscriptionPackage {
}


