/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SupervisorApprovalDTO { 
    supervisorId?: string;
    isApproved?: boolean;
    rejectionReason?: string | null;
}

