/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SupervisorApplicationDTO { 
    supervisorId?: string;
    schoolName?: string | null;
    contactPersonFirstName?: string | null;
    contactPersonLastName?: string | null;
    contactPersonEmail?: string | null;
    contactPersonPhone?: string | null;
    city?: string | null;
    address?: string | null;
    additionalInfo?: string | null;
}

