/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BillingInterval } from './billingInterval';


export interface SupervisorSubscriptionRequestDTO { 
    supervisorApplicationId?: string;
    subscriptionPackageId?: string;
    billingInterval?: BillingInterval;
}
export namespace SupervisorSubscriptionRequestDTO {
}


