/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DailyRegistrationDTO } from './dailyRegistrationDTO';
import { UserRole } from './userRole';


export interface UserRegistrationStatsDTO { 
    role?: UserRole;
    totalCount?: number;
    thisMonth?: number;
    thisWeek?: number;
    today?: number;
    last7Days?: Array<DailyRegistrationDTO> | null;
}
export namespace UserRegistrationStatsDTO {
}


