/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './payment';
import { UserRole } from './userRole';
import { Subscription } from './subscription';
import { ApprovalStatus } from './approvalStatus';


export interface User { 
    id?: string;
    email?: string | null;
    passwordHash?: string | null;
    role?: UserRole;
    approvalStatus?: ApprovalStatus;
    isEmailVerified?: boolean;
    emailVerificationToken?: string | null;
    emailVerificationTokenExpiry?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: string | null;
    currentClass?: string | null;
    school?: string | null;
    phoneNumber?: string | null;
    profession?: string | null;
    city?: string | null;
    postalCode?: string | null;
    isOneTimeLoginUsed?: boolean;
    mustChangePasswordOnNextLogin?: boolean;
    originalGeneratedPassword?: string | null;
    supervisorId?: string | null;
    supervisor?: User;
    supervisedUsers?: Array<User> | null;
    passwordResetToken?: string | null;
    passwordResetTokenExpiry?: string | null;
    refreshToken?: string | null;
    refreshTokenExpiry?: string | null;
    payments?: Array<Payment> | null;
    createAt?: string;
    parentUserId?: string | null;
    activeSubscriptionId?: string | null;
    activeSubscription?: Subscription;
    subscriptionExpiresAt?: string | null;
    readonly hasActiveSubscription?: boolean;
    subscriptions?: Array<Subscription> | null;
    childrenCount?: number;
    studentsCount?: number;
}
export namespace User {
}


