/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './payment';
import { UserRole } from './userRole';
import { ApprovalStatus } from './approvalStatus';


export interface User { 
    id?: string;
    email?: string | null;
    passwordHash?: string | null;
    role?: UserRole;
    approvalStatus?: ApprovalStatus;
    isEmailVerified?: boolean;
    emailVerificationToken?: string | null;
    emailVerificationTokenExpiry?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: string | null;
    currentClass?: string | null;
    school?: string | null;
    phoneNumber?: string | null;
    profession?: string | null;
    city?: string | null;
    postalCode?: string | null;
    passwordResetToken?: string | null;
    passwordResetTokenExpiry?: string | null;
    refreshToken?: string;
    refreshTokenExpiry?: string;
    payments?: Array<Payment> | null;
}
export namespace User {
}


