/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface UserGrowthDTO { 
    date?: string;
    newUsers?: number;
    totalUsers?: number;
    role?: UserRole;
}
export namespace UserGrowthDTO {
}


