/**
 * TeachingBACKEND API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ApprovalStatus = 0 | 1 | 2;

export const ApprovalStatus = {

    NUMBER_0: 0 as ApprovalStatus,

    NUMBER_1: 1 as ApprovalStatus,

    NUMBER_2: 2 as ApprovalStatus
};

